name: JS Tests
on:
  push:
    paths:
      - 'js/**'
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  run:
    name: JS Tests
    runs-on: ubuntu-latest

    steps:
      - name: Bail early
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'skip:ci')
        run: exit 0

      - name: Clone repository
        uses: actions/checkout@v3
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}
          cache: npm
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Install npm dependencies
        run: npm ci
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Run dist
        run: npm run js
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Run JS tests
        run: npm run js-test
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Run Coveralls
        uses: coverallsapp/github-action@1.1.3
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "./js/coverage/lcov.info"
