name: Lint
on:
  push:
    paths:
      - 'js/**'
      - 'scss/**'
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Bail early
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'skip:ci')
        run: exit 0

      - name: Clone repository
        uses: actions/checkout@v3
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
          cache: npm
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Install npm dependencies
        run: npm ci
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Lint
        run: npm run lint
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))
